/**
 * 细粒度样例：Agent 短期记忆解决方案（时间线梳理）
 * 对话含 {{cite:noteId}} 引用标记；画布节点可挂 noteId。
 */
import type { DemoEdge, DemoNode, DemoStep } from "./think-replay-types.ts";

const N = {
  intent: (id: string, label: string, x: number, y: number, sub?: string): DemoNode => ({
    id,
    label,
    sub,
    kind: "intent",
    x,
    y,
    badge: "问题",
  }),
  spine: (
    id: string,
    label: string,
    x: number,
    y: number,
    sub?: string,
    done?: boolean,
  ): DemoNode => ({
    id,
    label,
    sub,
    kind: "spine",
    x,
    y,
    badge: "时段",
    done,
  }),
  branch: (id: string, label: string, x: number, y: number, sub?: string): DemoNode => ({
    id,
    label,
    sub,
    kind: "branch",
    x,
    y,
    badge: "观点",
  }),
  note: (
    id: string,
    label: string,
    x: number,
    y: number,
    noteId: string,
    sub?: string,
  ): DemoNode => ({
    id,
    label,
    sub,
    kind: "note",
    x,
    y,
    badge: "笔记",
    noteId,
    done: true,
  }),
  action: (id: string, label: string, x: number, y: number, sub?: string): DemoNode => ({
    id,
    label,
    sub,
    kind: "action",
    x,
    y,
    badge: "收束",
    done: true,
  }),
  gate: (id: string, label: string, x: number, y: number, sub?: string): DemoNode => ({
    id,
    label,
    sub,
    kind: "gate",
    x,
    y,
    badge: "澄清",
  }),
};

function E(id: string, from: string, to: string, label?: string): DemoEdge {
  return { id, from, to, label };
}

/** 主样例剧本：短期记忆方案时间线 */
export const SCRIPT_AGENT_STM: DemoStep[] = [
  {
    id: "stm0",
    title: "细粒度提问",
    holdMs: 700,
    phase: "clarify",
    canvasHint: "等待细粒度意图…",
    chat: [
      {
        id: "stm-u0",
        role: "user",
        text: "我想知道 Agent memory 中短期记忆一般有哪些解决方案？最好按发展脉络讲清楚。",
      },
    ],
  },
  {
    id: "stm1",
    title: "澄清粒度",
    holdMs: 800,
    phase: "clarify",
    canvasHint: "切入点很细 · 先确认梳理轴",
    chat: [
      {
        id: "stm-t1",
        role: "thinking",
        text: "问题已足够具体。将全库检索「短期记忆 / sliding window / scratchpad / MemGPT / KV」等片段，即使用户笔记主题不是 Memory。默认按时间线组织；若用户只要清单可改并列。",
      },
      {
        id: "stm-a1",
        role: "assistant",
        text: "这个切入点很清晰。我准备按「时间演进」从仓库里抽相关片段来梳——很多笔记主题并不是 Memory，但正文里埋了可用段落。请确认一下组织轴：",
        options: [
          {
            id: "axis-time",
            level: "组织轴",
            label: "时间演进",
            desc: "窗口 → 摘要 → 工作区 → 检索 → 分层",
          },
          {
            id: "axis-trade",
            level: "组织轴",
            label: "代价对照",
            desc: "实现成本 / 保真度 / 可观测性",
          },
          {
            id: "scope-stm",
            level: "范围",
            label: "只谈短期",
            desc: "不展开长期知识库，除非边界需要",
          },
        ],
        autoPick: ["axis-time", "scope-stm"],
      },
    ],
    graph: {
      nodes: [N.gate("g0", "Agent 短期记忆？", 420, 200, "待确认组织轴")],
      edges: [],
    },
    highlightIds: ["g0"],
  },
  {
    id: "stm2",
    title: "确认并检索",
    holdMs: 700,
    phase: "draft",
    chat: [
      {
        id: "stm-u1",
        role: "user",
        text: "按时间演进，只谈短期；长期库只在边界处点一下。",
      },
      {
        id: "stm-t2",
        role: "thinking",
        text: "library_retrieve：命中 6 条笔记中的 11 个片段（含 2 张示意图）。开始按年代串主脊，叶节点挂笔记卡片。",
      },
    ],
  },
  {
    id: "stm3",
    title: "初版时间线",
    holdMs: 1200,
    phase: "draft",
    canvasHint: "主脊：短期记忆方案时间线 · 叶节点=笔记卡片",
    chat: [
      {
        id: "stm-a2",
        role: "assistant",
        text: "我从仓库抽了相关片段，按时间串成一条主逻辑。先看总览：\n\n**① 滑动窗口（最早）**——把最近 K 轮原文塞进 context，超出就截断。{{cite:note-buffer-window}} 这是几乎所有早期 Agent 的默认短期记忆。\n\n**② 递归摘要**——窗口要溢出时，把旧轮次压成摘要写回 memory 槽，用压缩换更长的「有效短期」。{{cite:note-summary-memory}}\n\n**③ Scratchpad 工作记忆**——把正在算的规划/中间 JSON 外置到可读写草稿区，而不是只活在隐式对话里。{{cite:note-scratchpad}}\n\n**④ 检索式短期**——近端轨迹进向量库，每轮召回 top-k 片段；不保证连续，但能跨窗口找回约束。{{cite:note-retrieval-stm}}\n\n**⑤ 分层记忆**——context≈RAM、库≈磁盘，短期变成「当前页+工作集」。{{cite:note-memgpt}}\n\n右侧画布已铺开；悬停引用角标或笔记节点可预览卡片，点击打开完整笔记（相关片段已标黄）。",
      },
    ],
    graph: {
      nodes: [
        N.intent("i0", "短期记忆有哪些解？", 380, 30, "Agent Memory · 时间线"),
        N.spine("s1", "① 滑动窗口", 380, 140, "2023 · 原样最近 K 轮", true),
        N.spine("s2", "② 递归摘要", 380, 260, "2023–24 · 压缩换长度", true),
        N.spine("s3", "③ Scratchpad", 380, 380, "2024 · 外置工作记忆", true),
        N.spine("s4", "④ 检索式 STM", 380, 500, "2024–25 · 轨迹召回", true),
        N.spine("s5", "⑤ 分层 page-in/out", 380, 620, "2024–25 · RAM/磁盘隐喻", true),
        N.branch("b1", "实现极简，易丢约束", 620, 120, "AI 总结"),
        N.branch("b2", "保真↑ 但有摘要幻觉", 620, 240, "AI 总结"),
        N.branch("b3", "状态显式化，需过期策略", 620, 360, "AI 总结"),
        N.branch("b4", "跨窗口召回，要时间衰减", 620, 480, "AI 总结"),
        N.branch("b5", "短期=工作集边界问题", 620, 600, "AI 总结"),
        N.note("n1", "对话缓冲笔记", 820, 100, "note-buffer-window", "片段×2"),
        N.note("n2", "Harness 摘要节", 820, 220, "note-summary-memory", "片段×2"),
        N.note("n3", "Skill 路由旁支", 820, 340, "note-scratchpad", "片段×3"),
        N.note("n4", "RAG 旁支·轨迹", 820, 460, "note-retrieval-stm", "片段×2"),
        N.note("n5", "Skills 综述·分层", 820, 580, "note-memgpt", "片段×2"),
      ],
      edges: [
        E("e0", "i0", "s1"),
        E("e1", "s1", "s2", "演进"),
        E("e2", "s2", "s3"),
        E("e3", "s3", "s4"),
        E("e4", "s4", "s5"),
        E("e1b", "s1", "b1"),
        E("e2b", "s2", "b2"),
        E("e3b", "s3", "b3"),
        E("e4b", "s4", "b4"),
        E("e5b", "s5", "b5"),
        E("en1", "b1", "n1"),
        E("en2", "b2", "n2"),
        E("en3", "b3", "n3"),
        E("en4", "b4", "n4"),
        E("en5", "b5", "n5"),
      ],
    },
    highlightIds: ["s1", "s2", "s3", "s4", "s5", "n1", "n2", "n3", "n4", "n5"],
  },
  {
    id: "stm4",
    title: "用户追问隐形损耗",
    holdMs: 750,
    phase: "extend",
    chat: [
      {
        id: "stm-u2",
        role: "user",
        text: "推理侧的 KV 压缩算不算短期记忆方案？感觉窗口看起来还在，模型却忘了。",
      },
    ],
  },
  {
    id: "stm5",
    title: "补分支·有效短期",
    holdMs: 1000,
    phase: "extend",
    canvasHint: "已延伸：名义窗口 ≠ 有效短期",
    chat: [
      {
        id: "stm-a3",
        role: "assistant",
        text: "算「有效短期」的约束层，而不是又一种拼装策略。白皮书片段写得很直白：Attention sink、流式 KV 淘汰会让名义上仍在窗口里的 token 权重趋近于零。{{cite:note-kv-attention}}\n\n所以评测短期记忆时，要同时看 **prompt 拼装** 与 **推理栈是否静默丢前缀**。我在主脊右侧加了一条「有效短期」支线，并挂上对应笔记卡。",
      },
    ],
    graph: {
      nodes: [
        N.intent("i0", "短期记忆有哪些解？", 380, 30, "Agent Memory · 时间线"),
        N.spine("s1", "① 滑动窗口", 380, 140, "2023 · 原样最近 K 轮", true),
        N.spine("s2", "② 递归摘要", 380, 260, "2023–24 · 压缩换长度", true),
        N.spine("s3", "③ Scratchpad", 380, 380, "2024 · 外置工作记忆", true),
        N.spine("s4", "④ 检索式 STM", 380, 500, "2024–25 · 轨迹召回", true),
        N.spine("s5", "⑤ 分层 page-in/out", 380, 620, "2024–25 · RAM/磁盘隐喻", true),
        N.branch("b1", "实现极简，易丢约束", 620, 120, "AI 总结"),
        N.branch("b2", "保真↑ 但有摘要幻觉", 620, 240, "AI 总结"),
        N.branch("b3", "状态显式化，需过期策略", 620, 360, "AI 总结"),
        N.branch("b4", "跨窗口召回，要时间衰减", 620, 480, "AI 总结"),
        N.branch("b5", "短期=工作集边界问题", 620, 600, "AI 总结"),
        N.branch("b6", "名义窗口 ≠ 有效注意", 200, 500, "推理侧约束"),
        N.note("n1", "对话缓冲笔记", 820, 100, "note-buffer-window", "片段×2"),
        N.note("n2", "Harness 摘要节", 820, 220, "note-summary-memory", "片段×2"),
        N.note("n3", "Skill 路由旁支", 820, 340, "note-scratchpad", "片段×3"),
        N.note("n4", "RAG 旁支·轨迹", 820, 460, "note-retrieval-stm", "片段×2"),
        N.note("n5", "Skills 综述·分层", 820, 580, "note-memgpt", "片段×2"),
        N.note("n6", "KV/注意力摘录", 40, 480, "note-kv-attention", "片段×2"),
      ],
      edges: [
        E("e0", "i0", "s1"),
        E("e1", "s1", "s2", "演进"),
        E("e2", "s2", "s3"),
        E("e3", "s3", "s4"),
        E("e4", "s4", "s5"),
        E("e1b", "s1", "b1"),
        E("e2b", "s2", "b2"),
        E("e3b", "s3", "b3"),
        E("e4b", "s4", "b4"),
        E("e5b", "s5", "b5"),
        E("e6b", "s4", "b6", "延伸"),
        E("en1", "b1", "n1"),
        E("en2", "b2", "n2"),
        E("en3", "b3", "n3"),
        E("en4", "b4", "n4"),
        E("en5", "b5", "n5"),
        E("en6", "b6", "n6"),
      ],
    },
    highlightIds: ["b6", "n6"],
  },
  {
    id: "stm6",
    title: "收束选型",
    holdMs: 900,
    phase: "final",
    canvasHint: "已收束 · 点击笔记节点打开右半屏详情",
    chat: [
      {
        id: "stm-u3",
        role: "user",
        text: "给我一个选型收束：个人助手场景优先用哪几层？",
      },
      {
        id: "stm-a4",
        role: "assistant",
        text: "按仓库片段的共识，个人助手的最小可跑组合是：\n\n1. **滑动窗口钉住硬约束**（人设/安全）{{cite:note-buffer-window}}  \n2. **facts/narrative 分槽摘要** 防溢出 {{cite:note-summary-memory}}  \n3. **Scratchpad** 扛多步工具状态 {{cite:note-scratchpad}}  \n4. 需要跨会话再上 **分层 page-in** {{cite:note-memgpt}}  \n5. 全程警惕 **KV 有效短期** 与名义窗口不一致 {{cite:note-kv-attention}}\n\n右侧终点节点已挂「选型清单」。点任意笔记小卡 → 右半屏展开全文，相关片段已黄标；鼠标移回左半对话区侧栏会自动收起。",
      },
    ],
    graph: {
      nodes: [
        N.intent("i0", "短期记忆有哪些解？", 380, 20, "Agent Memory · 时间线"),
        N.spine("s1", "① 滑动窗口", 380, 120, "2023 · 原样最近 K 轮", true),
        N.spine("s2", "② 递归摘要", 380, 230, "2023–24 · 压缩换长度", true),
        N.spine("s3", "③ Scratchpad", 380, 340, "2024 · 外置工作记忆", true),
        N.spine("s4", "④ 检索式 STM", 380, 450, "2024–25 · 轨迹召回", true),
        N.spine("s5", "⑤ 分层 page-in/out", 380, 560, "2024–25 · RAM/磁盘隐喻", true),
        N.action("a0", "个人助手选型清单", 380, 680, "钉约束 · 分槽摘要 · 草稿 · 分层"),
        N.branch("b1", "实现极简，易丢约束", 620, 100, "AI 总结"),
        N.branch("b2", "保真↑ 但有摘要幻觉", 620, 210, "AI 总结"),
        N.branch("b3", "状态显式化，需过期策略", 620, 320, "AI 总结"),
        N.branch("b4", "跨窗口召回，要时间衰减", 620, 430, "AI 总结"),
        N.branch("b5", "短期=工作集边界问题", 620, 540, "AI 总结"),
        N.branch("b6", "名义窗口 ≠ 有效注意", 180, 450, "推理侧约束"),
        N.note("n1", "对话缓冲笔记", 840, 80, "note-buffer-window", "片段×2"),
        N.note("n2", "Harness 摘要节", 840, 190, "note-summary-memory", "片段×2"),
        N.note("n3", "Skill 路由旁支", 840, 300, "note-scratchpad", "片段×3"),
        N.note("n4", "RAG 旁支·轨迹", 840, 410, "note-retrieval-stm", "片段×2"),
        N.note("n5", "Skills 综述·分层", 840, 520, "note-memgpt", "片段×2"),
        N.note("n6", "KV/注意力摘录", 40, 430, "note-kv-attention", "片段×2"),
      ],
      edges: [
        E("e0", "i0", "s1"),
        E("e1", "s1", "s2", "演进"),
        E("e2", "s2", "s3"),
        E("e3", "s3", "s4"),
        E("e4", "s4", "s5"),
        E("e5", "s5", "a0", "收束"),
        E("e1b", "s1", "b1"),
        E("e2b", "s2", "b2"),
        E("e3b", "s3", "b3"),
        E("e4b", "s4", "b4"),
        E("e5b", "s5", "b5"),
        E("e6b", "s4", "b6", "延伸"),
        E("en1", "b1", "n1"),
        E("en2", "b2", "n2"),
        E("en3", "b3", "n3"),
        E("en4", "b4", "n4"),
        E("en5", "b5", "n5"),
        E("en6", "b6", "n6"),
      ],
    },
    highlightIds: ["a0"],
  },
];

export const STM_SESSION_META = {
  id: "ws-stm",
  title: "Agent 短期记忆",
  subtitle: "细切入 · 时间线方案",
  branch: "问题：短期记忆有哪些解决方案？",
  canvasTitle: "短期记忆方案时间线",
  when: "刚刚",
};
