import type { TourCommand, TourRoute } from "./tour-bus";

export type TourStep = {
  id: string;
  phase: string;
  title: string;
  /** 用户痛点 */
  pain?: string;
  /** 产品特色 / 设计决策 */
  feature?: string;
  /** 旁白 */
  say: string;
  /** 交互式模式下给用户的动作提示 */
  guide?: string;
  /** 该步骤需要注意的细节 */
  details?: string[];
  route: TourRoute;
  /** CSS / [data-tour=…] */
  target?: string;
  /** 自动停留毫秒 */
  wait: number;
  enter?: TourCommand[];
  leave?: TourCommand[];
  /** 进入后额外等待（等页面动画） */
  settleMs?: number;
};

/**
 * 完整产品双模式演示脚本（真手机壳 + 真网页工作台）
 * 叙事：收下 → 对齐领域 → 确认用途 → 切片看见 → 梳成逻辑
 */
export const PRODUCT_TOUR_STEPS: TourStep[] = [
  {
    id: "hub-loop",
    phase: "开场 · 闭环",
    title: "明晰要解决的，不是「再多一个收藏夹」",
    pain: "痛点：小红书 / 微信 / PDF / 网页随手存，月底打开却想不起「当初存它要干嘛」——收藏 ≠ 可用知识。",
    feature: "产品闭环：手机先收下 → AI 对齐领域 → 人确认用途 → 网页按意图切片 → 梳逻辑线变成可执行判断。",
    say: "接下来在真实 Demo 里按产品顺序走完整链路，两端功能都不省略。",
    route: "/demo",
    target: "[data-tour=hub-hero]",
    wait: 6200,
  },
  {
    id: "principle-c1c2",
    phase: "原则 · C1/C2",
    title: "领域交给 AI，用途由人点",
    pain: "痛点：让模型猜「你为什么存」最容易错；猜错了后面整理全歪。",
    feature: "C1 知识领域全自动；C2 用途（学习 / 避雷 / 素材…）以人为主。短按可以不决策，标「待定」也不堵捕获。",
    say: "这是整条产品逻辑的地基——捕获要快，决策可以延后，但必须能回流确认。",
    route: "/demo",
    target: "[data-tour=hub-principles]",
    wait: 5800,
  },
  {
    id: "phone-home",
    phase: "手机 · 桌面",
    title: "在真实 App 场景里捕获，而不是另开表单",
    feature: "OPPO 高保真壳：桌面 → 小红书 / B站 / 微信，悬浮球挂在内容旁。",
    say: "先回到手机桌面。捕获发生在你正在阅读的地方——目标是「不打断阅读」。",
    route: "/demo/phone",
    target: "[data-tour=phone-shell]",
    wait: 4200,
    settleMs: 600,
    enter: [{ type: "phone.home" }, { type: "phone.openInbox", on: false }, { type: "phone.closeFan" }],
  },
  {
    id: "phone-xhs-feed",
    phase: "手机 · 场景",
    title: "打开小红书：灵感就在信息流里",
    say: "进入小红书发现流。产品不要求你复制粘贴到别处——球跟着场景走。",
    route: "/demo/phone",
    target: "[data-tour=phone-shell]",
    wait: 3800,
    enter: [{ type: "phone.goto", screens: ["library", "xhs-feed"] }],
  },
  {
    id: "phone-xhs-post",
    phase: "手机 · 帖子",
    title: "点进帖子：上下文完整保留",
    say: "打开一条高信息密度帖。标题、来源 App、后续领域建议，都会作为捕获上下文带走。",
    route: "/demo/phone",
    target: "[data-tour=phone-shell]",
    wait: 4000,
    enter: [{ type: "phone.goto", screens: ["library", "xhs-feed", "xhs-post"] }],
  },
  {
    id: "phone-tap-park",
    phase: "手机 · 截图",
    title: "方法一：直接截图保存",
    pain: "痛点：来不及细选内容时，复制和整理会打断阅读。",
    feature: "没有文字选区时，短按悬浮球直接保存当前页面截图，用途先放入待定。",
    say: "帖子保持原样、没有任何预先划线。先演示无选区短按，直接截下当前页面。",
    route: "/demo/phone",
    target: "[data-tour=float-ball]",
    wait: 5200,
    enter: [
      { type: "phone.selectText", text: null },
      { type: "phone.pulseBall", on: true },
      { type: "phone.capture", purposeId: "park" },
    ],
    leave: [{ type: "phone.pulseBall", on: false }],
  },
  {
    id: "phone-select",
    phase: "手机 · 划词",
    title: "方法二：手动选中一段文字",
    pain: "痛点：整页截屏噪声大，回顾时找不到真正重要的句子。",
    feature: "用户主动划词后，黄色选区才从左到右出现；原帖默认没有高亮。",
    say: "现在手动选中正文里的“工具协议与安全边界”，选区动画只在这一步出现。",
    route: "/demo/phone",
    target: ".sim-sel.is-on",
    wait: 4300,
    enter: [
      { type: "phone.selectText", text: "工具协议与安全边界" },
    ],
  },
  {
    id: "phone-save-selection",
    phase: "手机 · 保存选区",
    title: "选中以后，再点击悬浮球保存",
    feature: "有选区时优先保存文字摘录，不再保存整页截图；标题和来源上下文仍会一起入库。",
    say: "完成选中后再点悬浮球，系统保存这段文字，并保留它来自哪篇帖子。",
    route: "/demo/phone",
    target: "[data-tour=float-ball]",
    wait: 4800,
    enter: [
      { type: "phone.pulseBall", on: true },
      { type: "phone.capture", purposeId: "park" },
    ],
    leave: [{ type: "phone.pulseBall", on: false }, { type: "phone.selectText", text: null }],
  },
  {
    id: "phone-fan",
    phase: "手机 · 长按扇区",
    title: "有空时再声明用途（C2 扇区）",
    feature: "长按展开：学习理论 / 资料收藏 / 反例避坑 / 对标拆解 / 素材金句 / 待定 / 语音新建。",
    say: "人选了具体用途，才能直接走对应成件配方。待定是出口，不是终点。",
    route: "/demo/phone",
    target: "[data-tour=purpose-fan]",
    wait: 5600,
    enter: [
      { type: "phone.goto", screens: ["library", "xhs-feed", "xhs-post"] },
      { type: "phone.openFan" },
    ],
    leave: [{ type: "phone.closeFan" }],
  },
  {
    id: "phone-capture-purpose",
    phase: "手机 · 带用途入库",
    title: "演示：直接存成「反例避坑」",
    say: "当你明确「这是避雷」时，长按选扇区一步到位——减少事后整理成本。",
    route: "/demo/phone",
    target: "[data-tour=float-ball]",
    wait: 4800,
    enter: [
      { type: "phone.closeFan" },
      { type: "phone.capture", purposeId: "counter" },
    ],
  },
  {
    id: "phone-voice",
    phase: "手机 · 语音新建用途",
    title: "用途词表不够时：按住说话新建",
    feature: "「新建用途」长按听写 → 识别 → 盖章保存。C2 可生长，不被预设锁死。",
    say: "演示语音命名流程动画：听写 → 识别 → 盖章入库。",
    route: "/demo/phone",
    target: "[data-tour=float-ball]",
    wait: 6200,
    enter: [{ type: "phone.openFan" }, { type: "phone.startVoice" }],
    leave: [{ type: "phone.closeFan" }],
  },
  {
    id: "phone-wechat-pdf",
    phase: "手机 · 微信 PDF",
    title: "跨 App：微信群文件也能整篇收藏",
    feature: "微信 → 工作群 → PDF 阅读器；无选区短按=截屏，PDF 场景可整篇收藏。",
    say: "真实工作流往往跨 App。明晰要覆盖「聊天里丢过来的论文」，而不仅是信息流。",
    route: "/demo/phone",
    target: "[data-tour=phone-shell]",
    wait: 5200,
    enter: [
      {
        type: "phone.goto",
        screens: ["library", "wx-chats", "wx-group", "wx-pdf"],
      },
      { type: "phone.closeFan" },
    ],
  },
  {
    id: "phone-pdf-capture",
    phase: "手机 · PDF 入库",
    title: "整篇 PDF · 用途「学习理论」",
    say: "论文类材料常走「学习理论」。领域稍后由 AI 对齐到骨干本体。",
    route: "/demo/phone",
    target: "[data-tour=float-ball]",
    wait: 4800,
    enter: [{ type: "phone.capture", purposeId: "concept" }],
  },
  {
    id: "phone-inbox",
    phase: "手机 · 笔记库",
    title: "待定不会消失：回流确认是自进化入口",
    pain: "痛点：待定笔记一堆，没有回流确认，知识库永远是收件箱。",
    feature: "笔记库展示待定 / 人声明用途 / 领域识别中→完成。确认写入用途先验。",
    say: "打开手机侧笔记库：刚收下的卡片都在。下一步去网页把「待定」长成结构。",
    route: "/demo/phone",
    target: "[data-tour=phone-inbox]",
    wait: 5600,
    enter: [{ type: "phone.openInbox", on: true }],
    leave: [{ type: "phone.openInbox", on: false }],
  },
  {
    id: "web-enter",
    phase: "网页 · 切换",
    title: "灵感进库之后，在网页长成知识",
    feature: "手机负责捕获；网页负责浏览、用途切片、领域覆盖、梳逻辑。",
    say: "切到完整网页工作台——这是银标库 + API 的真页面，不是精简 HTML。",
    route: "/mingxi/web",
    target: "[data-tour=web-brand]",
    wait: 4500,
    settleMs: 900,
    enter: [
      { type: "web.setView", view: "library" },
      { type: "web.setPurpose", purpose: "全部" },
      { type: "web.closeNote" },
      { type: "web.setCapture", on: false },
      { type: "web.setEval", on: false },
    ],
  },
  {
    id: "web-navigation",
    phase: "网页 · 导航",
    title: "四个工作区，各自回答一种问题",
    feature: "笔记库负责找材料；领域旭日负责看结构；梳逻辑线负责形成判断；扩展负责发现并补齐缺口。",
    say: "先认清顶部四个入口。它们不是四个孤立页面，而是从材料、结构、推理到补全的一条工作链。",
    guide: "依次点击顶部四个标签感受切换，最后回到「笔记库」，再进入下一步。",
    details: ["笔记库：搜索、筛选与阅读", "领域旭日：全局知识结构", "梳逻辑线：对话与逻辑画布", "扩展：证据化知识补全"],
    route: "/mingxi/web",
    target: "[data-tour=web-tabs]",
    wait: 6200,
    enter: [{ type: "web.setView", view: "library" }],
  },
  {
    id: "web-ask",
    phase: "网页 · 问明晰",
    title: "顶部意图入口：从问题跳进梳逻辑",
    feature: "「问明晰」把自然语言意图接到梳逻辑线；也可一键跑回忆 Demo。",
    say: "捕获只是原料。真正价值是：带着问题，从自己的库里梳出一条可用逻辑。",
    route: "/mingxi/web",
    target: "[data-tour=web-ask]",
    wait: 4800,
    enter: [{ type: "web.focusAsk" }],
  },
  {
    id: "web-search",
    phase: "网页 · 全库搜索",
    title: "搜索标题、领域和摘要",
    feature: "搜索与用途、领域筛选可以叠加；按 Enter 执行，不会丢失当前用途上下文。",
    say: "如果你已经记得一个关键词，直接搜索比浏览更快。搜索不是独立入口，而是当前切片上的进一步收窄。",
    guide: "点击搜索框，输入任意关键词并按 Enter；体验结果后可清空，再点击下一步。",
    details: ["匹配标题", "匹配领域路径", "匹配笔记摘要"],
    route: "/mingxi/web",
    target: "[data-tour=web-search]",
    wait: 5200,
    enter: [{ type: "web.setView", view: "library" }, { type: "web.setPurpose", purpose: "全部" }],
  },
  {
    id: "web-purpose",
    phase: "网页 · 用途切片",
    title: "按「对我有什么用」切片，不是按 App 来源",
    pain: "痛点：收藏夹按 App / 时间堆，找不到「我存来避雷」的那批。",
    feature: "C2 chips 可增删排序；换用途，卡片与左侧领域分布一起变。",
    say: "切到「反例避坑」——同一批内容，换意图轴，看见的结构就不同。",
    route: "/mingxi/web",
    target: "[data-tour=purpose-chips]",
    wait: 5200,
    enter: [{ type: "web.setView", view: "library" }, { type: "web.setPurpose", purpose: "反例避坑" }],
  },
  {
    id: "web-purpose-manage",
    phase: "网页 · 用途管理",
    title: "用途标签可以新增、排序，也可以移除",
    feature: "点击「+ 新增」创建个人用途；长按已有用途进入拖动，拖到回收区即可移除。",
    say: "C2 用途不是固定分类表，而是跟着人的工作方式生长。系统保留默认词表，也允许你建立自己的语言。",
    guide: "点击「+ 新增」查看输入流程；也可以长按任一用途标签体验排序。无需保存即可继续。",
    details: ["新增用途保存在当前浏览器", "长按 420ms 进入排序", "移除用途不会删除笔记正文"],
    route: "/mingxi/web",
    target: "[data-tour=purpose-chips]",
    wait: 6200,
    enter: [{ type: "web.setView", view: "library" }, { type: "web.setPurpose", purpose: "全部" }],
  },
  {
    id: "web-heat",
    phase: "网页 · 领域热力",
    title: "热力：看见分布，也看见缺口",
    feature: "对照 C1 骨干：有笔记的格子变深，空格是覆盖缺口。",
    say: "特色不是又一个标签云，而是告诉你在当前用途下，知识版图哪里厚、哪里空。",
    route: "/mingxi/web",
    target: "[data-tour=domain-rail]",
    wait: 5600,
    enter: [
      { type: "web.setPurpose", purpose: "全部" },
      { type: "web.setDomainViz", viz: "heat" },
      { type: "web.setDomainFilter", path: null },
    ],
  },
  {
    id: "web-icicle",
    phase: "网页 · Icicle",
    title: "Icicle：一眼看层级占比",
    feature: "热力强调覆盖缺口；Icicle 强调有笔记领域的结构占比——同一数据，两种读法。",
    say: "切换可视化版本。小格子也会标篇数，避免「空白误读」。",
    route: "/mingxi/web",
    target: "[data-tour=domain-rail]",
    wait: 5200,
    enter: [{ type: "web.setDomainViz", viz: "icicle" }],
  },
  {
    id: "web-domain-filter",
    phase: "网页 · 领域下钻",
    title: "点领域 → 卡片跟着收窄",
    say: "用途 × 领域双轴过滤：先问「对我有什么用」，再问「落在哪块知识」。",
    route: "/mingxi/web",
    target: "[data-tour=note-grid]",
    wait: 4800,
    enter: [
      { type: "web.setDomainViz", viz: "heat" },
      { type: "web.setDomainFilter", path: ["工学", "计算机科学与技术"] },
    ],
    leave: [{ type: "web.setDomainFilter", path: null }],
  },
  {
    id: "web-card-anatomy",
    phase: "网页 · 卡片细节",
    title: "一张卡片同时保留来源、判断和分类",
    feature: "卡片不只显示摘要：内容形态、一级领域、用途、日期、立场与完整领域路径都可快速扫读。",
    say: "先在列表层判断它值不值得打开，再进入正文。这样能减少反复点开、返回的浏览成本。",
    guide: "把鼠标移到不同卡片上，观察顶部标签、判断色与底部领域路径；点击任一卡片可进入正文。",
    details: ["顶部：内容形态与领域", "中部：日期、立场、标题和摘要", "底部：可追溯的领域路径"],
    route: "/mingxi/web",
    target: "[data-tour=note-grid]",
    wait: 6200,
    enter: [
      { type: "web.setView", view: "library" },
      { type: "web.setPurpose", purpose: "全部" },
      { type: "web.setDomainFilter", path: null },
    ],
  },
  {
    id: "web-note",
    phase: "网页 · 笔记页",
    title: "点开是完整笔记，不是摘要碎片",
    feature: "独立全屏阅读；用途、目标、形态、判断与领域标签分类展示。",
    say: "捕获物要长成「可引用的笔记」，才能支撑后面梳逻辑与证据回溯。",
    route: "/mingxi/web",
    target: "[data-tour=note-drawer]",
    wait: 5600,
    enter: [
      { type: "web.setPurpose", purpose: "全部" },
      { type: "web.setDomainFilter", path: null },
      { type: "web.openNote", index: 0 },
    ],
  },
  {
    id: "web-atlas",
    phase: "网页 · 旭日图",
    title: "知识领域旭日：全局鸟瞰",
    feature: "DomainFanAtlas：按骨干本体扇形展开，点击扇区进入笔记。",
    say: "从列表视角切到全局地图——适合发现结构，而不是只翻时间线。",
    route: "/mingxi/web",
    target: "[data-tour=web-atlas]",
    wait: 5600,
    enter: [{ type: "web.closeNote" }, { type: "web.setView", view: "atlas" }],
  },
  {
    id: "web-atlas-controls",
    phase: "网页 · 旭日控制",
    title: "旋转、平移、缩放、密度与笔记开关",
    feature: "中心始终锁定；可在旋转/平移模式间切换，调节 25%–400% 缩放、节点疏密和外圈笔记显示。",
    say: "这套工具栏专门解决大图浏览：先用「适应」看全局，再放大局部；标签不会再被方形边界挤到底部。",
    guide: "依次试试旋转、平移、加减缩放、疏密下拉和「笔记开/关」，最后点击「适应」。",
    details: ["旋转围绕中心进行", "平移用于查看画布边缘", "适应会把可见标签重新收进屏幕"],
    route: "/mingxi/web",
    target: "[data-tour=atlas-toolbar]",
    wait: 7200,
    enter: [{ type: "web.setView", view: "atlas" }],
  },
  {
    id: "web-atlas-canvas",
    phase: "网页 · 旭日交互",
    title: "领域负责下钻，白色叶节点才打开笔记",
    feature: "拖动空白处旋转；点击领域进入子树；点击终端白色笔记节点进入左右分屏。",
    say: "自动版会演示一次旋转、放大与适应。交互版可以直接拖动画布，并选择任意领域下钻。",
    guide: "在空白区域拖动旋转，点击一个领域节点下钻，再用「总览 / 复位」返回全图。",
    details: ["领域节点只改变结构焦点", "笔记节点打开正文", "滚轮与双指手势都可缩放"],
    route: "/mingxi/web",
    target: "[data-tour=atlas-canvas]",
    wait: 7200,
    enter: [
      { type: "web.setView", view: "atlas" },
      { type: "web.clickTourTarget", target: "atlas-rotate-right" },
      { type: "web.clickTourTarget", target: "atlas-zoom-in" },
      { type: "web.clickTourTarget", target: "atlas-fit" },
    ],
  },
  {
    id: "web-purpose-confirm",
    phase: "网页 · 待定确认",
    title: "待定 → AI 候选 → 人点「就是它」",
    feature: "用途确认写入先验与画像信号；下次同类内容建议更贴习惯。",
    say: "自进化第一块地基：人确认过的用途，会回流成系统偏好——不是一次性标签。",
    guide: "选择一项系统建议或其他用途，再点击确认；也可以点「稍后再说」跳过本次决定。",
    details: ["系统建议会给出匹配依据", "最终选择权始终在人", "确认只改变分类，不改笔记正文"],
    route: "/mingxi/web",
    target: "[data-tour=purpose-confirm]",
    wait: 7000,
    settleMs: 700,
    enter: [
      { type: "web.setView", view: "library" },
      { type: "web.setPurpose", purpose: "待定" },
      { type: "web.openNote", purpose: "待定", index: 0 },
    ],
  },
  {
    id: "web-capture-drawer",
    phase: "网页 · 捕获抽屉",
    title: "网页也能入库：补齐跨端入口",
    feature: "侧栏捕获抽屉对接 /api/mingxi/capture，与手机同一套打标链路。",
    say: "桌面阅读论文、粘贴链接时，不必绕回手机——同一产品逻辑，双端入口。",
    route: "/mingxi/web",
    target: "[data-tour=capture-drawer]",
    wait: 5000,
    enter: [{ type: "web.setCapture", on: true }],
    leave: [{ type: "web.setCapture", on: false }],
  },
  {
    id: "web-completion-enter",
    phase: "扩展 · 目标边界",
    title: "知识补全先从一篇真实笔记出发",
    pain: "痛点：自动扩展很容易越搜越远，把相关概念、猜测和事实混成一团。",
    feature: "左侧先选定起点笔记，后续粒度、跳数、节点和联网结果都围绕同一份材料展开。",
    say: "进入扩展工作区。先固定起点，系统才知道该沿哪条知识脉络寻找缺口。",
    guide: "在左侧切换不同起点笔记，观察中间标题、知识分支和统计是否一起更新。",
    details: ["起点始终可见", "搜索可快速定位笔记", "切换起点会重建相邻知识路径"],
    route: "/mingxi/web",
    target: "[data-tour=completion-goal]",
    wait: 7200,
    enter: [{ type: "web.setView", view: "extend" }],
  },
  {
    id: "web-completion-metrics",
    phase: "扩展 · 掌握度",
    title: "粒度决定看多细，跳数决定走多远",
    feature: "主题级、概念级、原子级控制节点颗粒；1–6 跳控制扩散距离，并实时区分本库覆盖与知识缺口。",
    say: "这里把扩展边界做成显式控制，避免系统悄悄越搜越远。覆盖和缺口会随选择实时更新。",
    guide: "依次切换三种知识粒度，再点「继续延伸」增加一跳，观察覆盖与缺口数字变化。",
    details: ["起点不会因调参改变", "暖色节点已有证据", "灰色节点代表本库未覆盖"],
    route: "/mingxi/web",
    target: "[data-tour=completion-metrics]",
    wait: 6200,
    enter: [{ type: "web.setView", view: "extend" }],
  },
  {
    id: "web-completion-map",
    phase: "扩展 · 缺口地图",
    title: "每一跳都保留从起点到缺口的路径",
    feature: "知识按分支和跳数排布；暖色表示本篇或本库证据，灰色虚线节点才是需要联网补全的位置。",
    say: "缺口不是随意推荐，而是沿着可解释的知识分支，从起点一跳一跳走出来。",
    guide: "横向滚动多跳地图，点击一个暖色节点查看本库证据，再点击灰色节点启动联网搜索。",
    details: ["列表示第几跳", "行保持知识分支", "高亮路径连接起点与当前节点"],
    route: "/mingxi/web",
    target: "[data-tour=completion-map]",
    wait: 6600,
    enter: [{ type: "web.setView", view: "extend" }],
  },
  {
    id: "web-completion-loop",
    phase: "扩展 · 完整闭环",
    title: "灰色缺口 → 联网检索 → 阅读 → 保存为证据",
    feature: "右侧检查器区分本库证据与联网结果；搜索结果可展开阅读全文，由人确认后才保存成明晰笔记。",
    say: "真正的补全不是把搜索结果直接塞回库里，而是检索、阅读、判断，再由人决定是否保存。",
    guide: "点击灰色节点，在右侧切换搜索范围并打开一条结果；确认有价值后再保存为明晰笔记。",
    details: ["搜索范围可切换", "结果可阅读全文", "保存后原灰色节点会变为暖色"],
    route: "/mingxi/web",
    target: "[data-tour=completion-inspector]",
    wait: 9000,
    enter: [
      { type: "web.setView", view: "extend" },
      { type: "web.clickTourTarget", target: "completion-play" },
    ],
  },
  {
    id: "web-think-enter",
    phase: "梳逻辑 · 入口",
    title: "从「有一堆笔记」到「有一条可用逻辑」",
    pain: "痛点：知识库堆满了，临场决策仍靠记忆与临时搜索。",
    feature: "梳逻辑线：对话推进问题，右侧画布长出节点；可切换回忆 Demo / 实机 Agent。",
    say: "进入梳逻辑。先用「回忆 Demo」完整展示产品叙事与引用链路（无需 API Key）。",
    guide: "先查看顶部状态、回忆/暂停/重置按钮，再观察页面的历史、对话和画布三栏结构。",
    details: ["回忆：播放可复现样例", "暂停：保留当前节点状态", "重置：清空本次回放进度"],
    route: "/mingxi/web",
    target: "[data-tour=think-toolbar]",
    wait: 5200,
    enter: [
      { type: "web.setView", view: "think" },
      { type: "web.setThinkSurface", surface: "replay" },
    ],
  },
  {
    id: "web-think-history",
    phase: "梳逻辑 · 会话记忆",
    title: "每段对话绑定自己的逻辑画布",
    feature: "历史栏区分样例会话和个人会话；切换会话时，对话、节点、缩放与分支状态一起恢复。",
    say: "不是把所有问题堆在一张无限画布里。每个意图拥有独立上下文，需要时再回来继续。",
    guide: "点击不同样例会话，观察对话主题和画布是否随会话一起切换；也可点 + 新建空白会话。",
    details: ["样例会话可反复回忆", "有画布的会话带状态标记", "新会话不会污染旧逻辑"],
    route: "/mingxi/web",
    target: "[data-tour=think-history]",
    wait: 6200,
    enter: [{ type: "web.setView", view: "think" }, { type: "web.setThinkSurface", surface: "replay" }],
  },
  {
    id: "web-think-composer",
    phase: "梳逻辑 · 输入控制",
    title: "继续追问、联网搜索和收束报告都由人触发",
    feature: "输入框支持继续对话；联网搜索可开关；有逻辑节点后才能主动收束成报告。",
    say: "Agent 不应静默扩大信息边界。是否查公网、何时停止发散、何时产生成件，都留给用户决定。",
    guide: "点击「联网搜索」观察来源提示变化；输入一句问题但无需发送，然后继续下一步。",
    details: ["Enter 发送，Shift+Enter 换行", "联网开关区分本库与公开网页", "报告按钮在有节点后解锁"],
    route: "/mingxi/web",
    target: "[data-tour=think-composer]",
    wait: 6800,
    enter: [{ type: "web.setView", view: "think" }, { type: "web.setThinkSurface", surface: "replay" }],
  },
  {
    id: "web-think-play",
    phase: "梳逻辑 · 回忆播放",
    title: "自动播放：对话 + 画布 + 引用角标",
    feature: "脚本驱动：用户意图 → Agent 思考 → 节点生长 → 笔记引用可点开。",
    say: "正在播放完整回忆演示。注意右侧逻辑图如何随对话长出——结论要可追溯。",
    guide: "点击「回忆」播放；可随时暂停，点击对话中的引用角标查看来源笔记。",
    details: ["Messages 展示人机对话", "Thinking 展示过程摘要", "引用角标连接到原始笔记"],
    route: "/mingxi/web",
    target: "[data-tour=think-chat]",
    wait: 14000,
    enter: [{ type: "web.playThinkReplay" }],
  },
  {
    id: "web-think-canvas",
    phase: "梳逻辑 · 逻辑画布",
    title: "节点、连线、来源颜色和分支都可追溯",
    feature: "画布支持拖动节点、平移缩放和适应视图；本库与网页来源用不同颜色，关键关系在线上标注。",
    say: "这里不是概念散点图。节点要表达判断角色，连线要表达因果、对照或警告关系。",
    guide: "拖动一个节点，平移画布，再尝试 +、− 和「适应画布」；点击带引用的节点查看来源。",
    details: ["珊瑚色表示本库材料", "绿色表示公开网页结果", "虚线通常表示警告或待验证支路"],
    route: "/mingxi/web",
    target: "[data-tour=think-canvas]",
    wait: 7600,
    enter: [{ type: "web.setView", view: "think" }, { type: "web.setThinkSurface", surface: "replay" }],
  },
  {
    id: "web-eval",
    phase: "网页 · 评测",
    title: "评测面板：产品不是只靠感觉",
    feature: "意图 / 捕获 / Agent 脚本评测入口挂在工作台，方便校准与回归。",
    say: "工程侧能力也在同一工作台可见——演示完整，不藏后台。",
    route: "/mingxi/web",
    target: "[data-tour=eval-drawer]",
    wait: 4800,
    enter: [{ type: "web.setView", view: "library" }, { type: "web.setEval", on: true }],
    leave: [{ type: "web.setEval", on: false }],
  },
  {
    id: "close-loop",
    phase: "收束",
    title: "闭环：收下 → 对齐 → 确认 → 切片 → 梳链",
    feature:
      "短按不堵捕获；领域 AI 自动；用途人确认并累积先验；网页按用途/领域看见结构；梳逻辑把笔记变成可执行判断。",
    say: "完整产品演示结束。你可以返回两端继续自由体验，也可以切换另一种指引模式再走一遍。",
    route: "/demo",
    target: "[data-tour=hub-hero]",
    wait: 7000,
    enter: [{ type: "web.setEval", on: false }, { type: "web.setCapture", on: false }],
  },
];

export const TOUR_STEP_COUNT = PRODUCT_TOUR_STEPS.length;
